name: belajar_dart_packages
description: A starting point for Dart libraries or applications.

# Hal yang perlu dilakukan ketika upgrade package adalah mengubah version ke yang lebih tinggi.
# version: 1.0.0 # Ini versi awal
version: 1.5.0 # Setelah upgrade

# Ketika menggunakan git, disarankan menambahkan tag baru sesuai dengan version.

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
